2023-01-30 21:22:44,101: INFO _welcome-362 Bot: Intellectual film bot [@Intellectual_film_bot]
2023-01-30 21:22:44,101: INFO start_polling-358 Start polling.
2023-01-30 21:23:03,006: ERROR default_exception_handler-1752 Task exception was never retrieved
future: <Task finished name='Task-21' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\main.py", line 69, in func
    await bot.send_message(message.from_user.id, f'Подобрал на свой вкус: {mults[randint(0, len(mults))]}')
IndexError: list index out of range
2023-01-30 21:23:56,073: ERROR default_exception_handler-1752 Task exception was never retrieved
future: <Task finished name='Task-50' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\main.py", line 112, in dogs_handler
    await bot.send_message(message.from_user.id, f'Подобрал на свой вкус: {dogs[randint(0, len(dogs))]}')
IndexError: list index out of range
2023-01-30 21:24:02,309: ERROR default_exception_handler-1752 Task exception was never retrieved
future: <Task finished name='Task-62' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\main.py", line 108, in historic_handler
    await bot.send_message(message.from_user.id, f'Подобрал на свой вкус: {historic[randint(0, len(historic))]}')
IndexError: list index out of range
2023-01-30 21:24:06,258: ERROR default_exception_handler-1752 Task exception was never retrieved
future: <Task finished name='Task-76' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\main.py", line 104, in roman_handler
    await bot.send_message(message.from_user.id, f'Подобрал на свой вкус: {roman[randint(0, len(roman))]}')
IndexError: list index out of range
2023-01-30 21:24:07,738: INFO start_handler-23 user_id=548004940 user_bot=False user_message='/start'
2023-01-30 21:24:25,683: ERROR default_exception_handler-1752 Task exception was never retrieved
future: <Task finished name='Task-128' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\main.py", line 112, in dogs_handler
    await bot.send_message(message.from_user.id, f'Подобрал на свой вкус: {dogs[randint(0, len(dogs))]}')
IndexError: list index out of range
2023-01-30 21:25:50,693: ERROR default_exception_handler-1752 Task exception was never retrieved
future: <Task finished name='Task-147' coro=<Dispatcher._process_polling_updates() done, defined at C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 415, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 235, in process_updates
    return await asyncio.gather(*tasks)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 256, in process_update
    return await self.message_handlers.notify(update.message)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\venv\lib\site-packages\aiogram\dispatcher\handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "C:\Users\WayWayz\Work_Place\python_examples\sem10\main.py", line 112, in dogs_handler
    await bot.send_message(message.from_user.id, f'Подобрал на свой вкус: {dogs[randint(0, len(dogs))]}')
IndexError: list index out of range
2023-01-30 21:28:13,523: INFO stop_polling-433 Stop polling...
2023-01-30 21:28:13,523: WARNING start_polling-329 Goodbye!
